services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  server:
    build:
      context: .
      target: final
    restart: unless-stopped
    ports:
      - 4000:4000
    env_file: .env
    environment:
      - GIN_MODE=release
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    restart: unless-stopped
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=xfy
      - POSTGRES_DB=gymo
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: ./password.txt
